### ISSUE TITLE
Watchnixtoons2 Issue

### ISSUE THREAD

**Issue by ShakarSaleem** [doko-desuka/plugin.program.orderfavourites#1]
Hi big fan of your work. I'm sorry that I'm messaging from here instead of the other repository but it's close. If you could help me please. I've been trying to the latest dub black clover episode but it don't work, could it be that we have to wait for the provider or something. I appreciate your reply. Thanks

**Comment by ShakarSaleem** [comment]
It's working now. sorry for the worry.

**Comment by doko-desuka** [comment]
The WatchNixtoons2 and WSBeta add-ons have been discontinued. Whenever they break in the future, someone else will have to repair them

**Comment by ShakarSaleem** [comment]
Hello friend I accidentally removed the repository and tried to reinstall it again but the video add-on in the repository is not there could you help in any way. thanks.

I'm sorry to disturb you again
