### ISSUE TITLE
 I miss one function and that is "add categories".

### ISSUE THREAD

**Issue by ghost** [doko-desuka/plugin.program.orderfavourites#11]
It great plugin, but I miss one function and that is "add categories".
So you can sort your favorites even better.
I tried my hand at it, but the code doesn't seem to be quite right, I only ever get the first entry in favourite.xml.
Does anyone have any ideas?

What I added:
-----
Es tolles Plugin, aber mir fehlt eine Funktion und zwar "Kategorien hinzuzufügen".
So kann man seine Favoriten noch besser sortieren.
Ich habe mich daran versucht, aber der Code scheint nicht ganz korrekt zu sein, mir wird immer nur der ersten Eintrag in der favourite.xml angezeigt.
Hat jemand eine Idee?

Was ich hinzugefügt habe:

default.py

```
class CustomFavouritesDialog(xbmcgui.WindowXMLDialog):
.....
303: self.doCategory,
```

```
    def doReload(self):
....
    def doCategory(self):
        if xbmcgui.Dialog().yesno(
            'Kategoriename',
            'Kategoriename hinzufügen\nProceed?'
        ):
            # Eingabeaufforderung für den Kategorienamen
            keyboard = xbmc.Keyboard('', 'Kategoriename eingeben')
            keyboard.doModal()
            if keyboard.isConfirmed():
                category_name = keyboard.getText()
                # Hinzufügen des Eintrags in der favourites.xml-Datei
                file = xbmcvfs.File(FAVOURITES_PATH)
                contents = DECODE_STRING(file.read())

                xmlText = contents.replace('</favourites>', '   <favourite name="{}" thumb="URL">[B]===[{}]===[/B]</favourite>\n</favourites>'.format(category_name, category_name))

                if not xmlText:
                    return False
                try:
                    file = xbmcvfs.File(FAVOURITES_PATH, 'w')
                    file.write(xmlText)
                    file.close()
                except Exception as e:
                    raise Exception('ERROR: unable to write to the Favourites file. Nothing was saved.')
                return True

```

CustomFavouritesDialog.xml
```
<control type="grouplist">
....
                <control type="button" id="303">
                    <height>100</height>
                    <onleft>200</onleft>
                    <onright>100</onright>
                    <textcolor>white</textcolor>
                    <label>[B]Kategorie[/B]</label>
                    <align>center</align>
                    <texturefocus colordiffuse="FF12A0C7">BGWhite.png</texturefocus>
                    <texturenofocus colordiffuse="30FFFFFF">BGWhite.png</texturenofocus>
                </control>
```

I would be glad about any help.
----
Über Hilfe würde ich mich freuen.

**Comment by doko-desuka** [comment]
Hi SannyQ, I think you're after the Super Favourites add-on. It can create favourites "folders" that you can use as categories.

Kodi by itself doesn't support categorizing favorites, it keeps all favorites flat in the same list, as shown here: https://kodi.wiki/view/Favourites.xml

Super Favourites tries to go around that by doing what the same thing you're trying to do, putting things in folders and calling that a "category".  
The main thread for S.F. is this: https://forum.kodi.tv/showthread.php?tid=192662  
Supposedly, a Kodi 19 (Matrix) updated version is in here (check the ones with biggest version number / more recent changes): https://github.com/jmooremcc/Repository.jmooremcc/tree/master/plugin.program.super.favourites

**Comment by doko-desuka** [comment]
Whoops, I accidentally closed your issue. I'll leave this open as an "enhancement", if anyone wants to take a crack at it.  
I'm content with the state of the add-on for now.

**Comment by ghost** [comment]
Greetings,
first of all I must say that your plugin is great. I have been waiting for something like this for a long time and was glad to see that it finally exists.

Look: If you use Super Favourites now, you have to use several plugins again.

Maybe you can use some of my suggestion, maybe parts of my code will help you. I think if your plugin includes all the features you need, it will be even more awesome.

In any case, I take my hat off and thank you for your work!

**Comment by doko-desuka** [comment]
Hi. In my current circumstances, I can only work on this feature if I'm commissioned to do it (someone hires me for that).  
If you're interested at all, send me an email on `dokodesuka121@gmail.com`.

**Comment by doko-desuka** [comment]
Outside the scope of this add-on, you need a directory manager plugin.
