### ISSUE TITLE
File manager source url

### ISSUE THREAD

**Issue by deputydoobie** [doko-desuka/plugin.program.orderfavourites#12]
Looking for a source url I can put into the Kodi file manager so I can access this add-on like I access other add-ons like the crew exodus and ghost

**Comment by doko-desuka** [comment]
Hi,  
This doesn't receive enough frequent updates from me that it'd warrant such a thing (constantly keeping it up to date). It's stable and simple enough that it can be left as it is, and people can modify the code in their own copies of this add-on if they need anything extra.

**Comment by M-Borsch** [comment]
Based on @doko-desuka suggestion, I have forked a version to run in other skins (e.g. Confluence) created a couple repositories (one for the program addon) and I also built a full repository that will deliver the forked program addon. Here is the URL for the full repository: https://m-borsch.github.io/repository.kodi.mb/

**Comment by doko-desuka** [comment]
@deputydoobie add https://doko-desuka.github.io/ to your Kodi file sources by going to Settings > File Manager > Add source (use that link, and give it a name).  
After that, go to Add-ons > Add-ons browser (the open box icon on the top-left, Estuary skin) > Install from zip file > select that named source > find the zips for this add-on for either Leia and Matrix+. Select a zip to install it.
