### ISSUE TITLE
Missing operations

### ISSUE THREAD

**Issue by mcross** [doko-desuka/plugin.program.orderfavourites#14]
Please, add these missing operations:

- move to 1st position
- move to last position
- move to specific position

Thanks.

**Comment by doko-desuka** [comment]
Hi @mcross ,  
I don't really have time to volunteer for this. Tagging this as Help Wanted.

**Comment by doko-desuka** [comment]
@mcross when you have some time, give v1.5.2 a try.  
I've added those options as a context-menu (that is, right-click / long-press on each item to bring up the menu with those options).

**Comment by mcross** [comment]
Tested.

Everythings works file. Thanks YOU.
