### ISSUE TITLE
The watchnixtoons2 link dont have the video add-on part in the repository

### ISSUE THREAD

**Issue by ShakarSaleem** [doko-desuka/plugin.program.orderfavourites#2]
Hello friend
I'm sorry to bother you again but I accidentally removed the source and tried to reinstall it again but the video add-on in the repository is not there could you help in any way. thanks.

I'm sorry to disturb you again
Or could you tell me the website used

**Comment by doko-desuka** [comment]
Hi @ShakarSaleem, have you tried asking around the Addons4Kodi subreddit? They should help you find your way. Good luck!
