### ISSUE TITLE
Install from repository?

### ISSUE THREAD

**Issue by RvV1979** [doko-desuka/plugin.program.orderfavourites#5]
Hi, 
Probably silly question but what url can I use to install from repository? 
Thanks

**Comment by doko-desuka** [comment]
@RvV1979 Hi. Kodi works like this: once you install a repository, it will be there as a source of add-ons for you to install through that "Install From Repository" menu.

To install the repository you need to get the repository package, it's a zip file. Whether you do that by adding [the URL of a page with that repository package](https://doko-desuka.github.io/) to your Settings > File Manager screen, or by [manually downloading the package itself](https://github.com/doko-desuka/doko.repository/raw/master/doko.repository/doko.repository-0.1.0.zip), putting it in some USB flash drive and plugging it into your Kodi device so you can go to Add-ons > Install from zip file... > choosing that package and install it, the result will be the same.

PS: Those two links are what you're looking for, the first is the URL to a page with a link to the zip file, the second is the URL to the zip file itself.  

I'm going to close this issue but you can still comment on it in case you need more help.

**Comment by doko-desuka** [comment]
What some people don't know is that if you go the URL route, once you use that URL to download the repository package, you can safely delete the URL in your File Manager since the repository package is now installed in your Kodi device, the URL did its work and can be removed.

**Comment by RvV1979** [comment]
Thanks so much for the quick reply and support! The link url works perfectly. (FYI I had previously tried https://github.com/doko-desuka/doko.repository/releases as per the readme and that did not work).
