### ISSUE TITLE
Two issues with the Order Favourites add-on on Kodi 19

### ISSUE THREAD

**Issue by gigarepo** [doko-desuka/plugin.program.orderfavourites#6]
I tried the experimental branch of the Order Favourites add-on on Kodi 19.3 and it seems to works with two issues:

- The add-on has no icon, which seems unprofessional (minor issue but still should be fixed)

- When changing the order of the favorites and then clicking Save and exit the Kodi freezes for 10 seconds and then restart (critical issue)

This is a great and useful add-on but especially with the second issue, it can't be used on Kodi 19. 
Can you please fix it?

**Comment by doko-desuka** [comment]
Hi @gigarepo, thanks for testing this on Kodi 19+.
The icon problem can probably be fixed with a simple change, but the second problem is that kind of obscure error you have to debug a few times until you figure it out.

I don't personally use 19+ (I'm stuck on 18 Leia), I'll ask on the forums if anyone can help with that second problem.

**Comment by peno64** [comment]
@gigarepo 
The icon problem is solved with the change from @doko-desuka 
I would be glad to help to  solve the crash but I cannot simulate it. I tried under windows with kodi 19.3 and on a raspberry  pi  with kodi 19.1 (kodi 19.2 or 19.3 isn't available yet there). When I choose save & and close I get the messagebox  that it is saved almost immediately and then it freezes a second or 3 ( 7 on the  pi) but then it returns to kodi.
Can you post a kodi log file (debug mode enabled) and also specify on which device you have this and do you get  the messagebox that save was done or not and when you then restart kodi are the favourites reordened or not?

**Comment by peno64** [comment]
looking at the code, most probably the crash occurs when executing
xbmc.executebuiltin('LoadProfile(%s)' % xbmc.getInfoLabel('System.ProfileName'))
It is more likely this is a kodi 19 problem than an addon problem.

**Comment by peno64** [comment]
I had once a crash with it. I am sure this is a kodi issue that should be reported to them.
This was on my  pi and I also have a crash log file:

2021-10-31 10:33:34.137 T:1248    ERROR <general>: SETTINGS: Agent.register_agent
                                                   *********************************** Unhandled exception detected ***********************************
                                                   ####################################################################################################
                                                                                              Diagnostic info
                                                   ----------------------------------------------------------------------------------------------------
                                                   Exception type  : DBusError
                                                   Exception value : net.connman.Error.AlreadyExists -- Already exists
                                                   System info     : uname_result(system='Linux', node='LibreELEC4', release='5.10.52', version='#1 SMP Wed Aug 11 14:10:51 CEST 2021', machine='aarch64', processor='')
                                                   Python version  : 3.8.9 (default, Aug 11 2021, 14:14:24)  [GCC 10.2.0]
                                                   Kodi version    : 19.1 (19.1.0) Git:6402a50950ff6463042f8891ec4029c782730391
                                                   sys.argv        : ['']
                                                   ----------------------------------------------------------------------------------------------------
                                                   sys.path:
                                                   ['',
                                                    '/usr/share/kodi/addons/service.libreelec.settings',
                                                    '/usr/lib/python38.zip',
                                                    '/usr/lib/python3.8',
                                                    '/usr/lib/python3.8/lib-dynload',
                                                    '/usr/lib/python3.8/site-packages',
                                                    '/usr/share/kodi/addons/service.libreelec.settings/resources/lib',
                                                    '/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules']

This is really in the core of kodi itself while executing the LoadProfile command.

Maybe a work-around would be to not load the profile and give a message to the user that kodi must be restarted to take the changes in effect. Something  that is done in other programs also...

**Comment by peno64** [comment]
Reported the crash to kodi: https://github.com/xbmc/xbmc/issues/20431

**Comment by gigarepo** [comment]
> @gigarepo The icon problem is solved with the change from @doko-desuka I would be glad to help to solve the crash but I cannot simulate it. I tried under windows with kodi 19.3 and on a raspberry pi with kodi 19.1 (kodi 19.2 or 19.3 isn't available yet there). When I choose save & and close I get the messagebox that it is saved almost immediately and then it freezes a second or 3 ( 7 on the pi) but then it returns to kodi. Can you post a kodi log file (debug mode enabled) and also specify on which device you have this and do you get the messagebox that save was done or not and when you then restart kodi are the favourites reordened or not?

@peno64 Thanks for your help!

I saw that you already made some progress but in any case here are the answers to your questions:
My device is Minix u9-h
I get the messagebox "Save successful, press OK to continue..." and the favourites are reorders and saved after the restart.
It not sure it is a a crash but looks like a restart because I don't need to start the Kodi again.  What I see is that my add-on EZ Maintenance+ show a message "Maintainance clean completed" and this happens only when I start my Kodi.
My Kodi log is attached:
[kodi.log](https://github.com/doko-desuka/plugin.program.orderfavourites/files/7448598/kodi.log)
.

**Comment by peno64** [comment]
Well it's a crash of kodi and then the system automatically restarts kodi because of it.
Do you have it sometimes or always?

**Comment by gigarepo** [comment]
> Well it's a crash of kodi and then the system automatically restarts kodi because of it. Do you have it sometimes or always?

Thanks for clarifying that this is a crash.
It happens every time I run the add-on.

**Comment by peno64** [comment]
I can simulate the issue also just via a keyyboard shortcut, so even no addon needed...

**Comment by gigarepo** [comment]
> I can simulate the issue also just via a keyyboard shortcut, so even no addon needed...

I saw your comments about how to simulate it, so I guess now we need to wait for the Kodi team to fix it. 
I hope they will fix it soon.

**Comment by doko-desuka** [comment]
> Reported the crash to kodi: xbmc/xbmc#20431
> I can simulate the issue also just via a keyyboard shortcut, so even no addon needed...

@peno64  Thanks a lot for your Kodi 19 help!

I'm thinking we could make these changes to the add-on main menu in the meantime, as it'll take a while for any fix to be released:

**Save and reload**  
Rename the "Save and exit" item to "Save and reload", as that's a way clearer name.

**Save and quit**  
It saves your changes and quits Kodi. This can be done using either the ["Application.Quit" JSON-RPC command](https://kodi.wiki/view/JSON-RPC_API/v10#Application.Quit), or the [xbmc.executebuiltin("Quit")](https://kodi.wiki/view/List_of_built-in_functions#System_built-in.27s) action which I think do the same thing. Then you, the user, have to manually start Kodi again.

**Save only**  
It just saves the changes to the `favourites.xml` file. If you go and change your favourites from within Kodi (using the Delete, Move Up or Move Down commands), I think your changes will be overwritten because it must keep the favourites file loaded in memory, and that does not have your changes.

**Comment by Kovaelin** [comment]
I'm using 19 on a Fire Stick 4K. I don't see the icon fix, however Save and Reload seems to take a while, but doesn't crash Kodi.

**Comment by doko-desuka** [comment]
I'm closing this, since the changes talked about in https://github.com/doko-desuka/plugin.program.orderfavourites/issues/6#issuecomment-955955383 were implemented.  

If anyone still has problems please open a new issue of course.
