### ISSUE TITLE
Issue with 1.2.2 

### ISSUE THREAD

**Issue by htatla81** [doko-desuka/plugin.program.orderfavourites#8]
I’m using Order Favourites on Kodi 19.5 and updated 1.2.1 to your new 1.2.2 today after getting repo email update. Device is Fire Cube (2nd Gen)

For save function I now have 2 options where as before there was only 1 
1.  “Save & Reload” (new)
2. “Save & Exit” (as per original 1.2.1 option)

Issue description : choosing “Save and exit” no longer works - the changes do not appear on exiting the addon - this worked in 1.2.1

“save and reload” works - so perhaps you need to kill option 2 altogether?

**Comment by doko-desuka** [comment]
Are you getting the "Save successful. Press OK to end the add-on..." message? It should appear even with the "Save and exit" option, and it only shows if everything was saved successfully.

> choosing “Save and exit” no longer works - the changes do not appear on exiting the addon - this worked in 1.2.1

That wasn't supposed to happen on 1.2.1 though. That "Save and exit" option was for when reloading the user profile (which is a standard operation), would crash Kodi on some devices.  
So "Save and exit" just saves the favourites file and doesn't reload the user profile. For that to happen you need to exit Kodi and start it again.

**Comment by htatla81** [comment]
hi i think i didnt read the update notes as i read that "save and exit" option in 1.2.2 does not reload/refresh the UI on exit by design due to this causing issues on some devices. User must close and reload Kodi app to see the fave order changes. 

so on this basis - its working as designed we can probably close this issue on this basis - apols for any bother! Addon is great and my life saver!

@doko-desuka would you ever consider developing a new "super faves" app that allows folders and better sorting of faveourites? i bet if you forked it you could make it 100x better - would be awesome

**Comment by doko-desuka** [comment]
(I'm closing this issue since it's solved, but comments are still open.)

> would you ever consider developing a new "super faves" app that allows folders and better sorting of faveourites? i bet if you forked it you could make it 100x better - would be awesome

Hm, at the moment I don't have a need for a folder add-on, which is like the baseline requirement for me to work on something -- making it for myself first, and then if it's useful to the public I can clean it up and release it.  

I'm not gonna say it'd be easy, but have you considered modding it on your own? It's fun in a "puzzle" sort of way (the mind challenge), and the skill (coding with Python 3.0) is super useful with Kodi and other topics.

**Comment by htatla81** [comment]
I am a keen Kodi user and love researching and trying out helpful add-ons to enhance the overall experience but sadly the last time i did any coding was back in University while working on some crappy JS game we were assigned :)
That said i also would like, no, actually i need some mind challenges in 2023 for distraction sake - so i will certainly look into learning Python and you never know you might be using one of mine! pls forward any beginner resources you think may be helpful

Take care and you are doing a great job with your repo

**Comment by doko-desuka** [comment]
Thanks, good luck.

There's three things you need to build skills on:  
1. Software programming in general (different design patterns, ways to do things etc);
2. How to implement your designs in Python (how Python works, the libraries and modules that you have access to etc);
3. How to implement your designs in Kodi (the Kodi API, its peculiarities etc).

You can build skills on 1 and 2 with online resources.  
For part 3 (Kodi and its API), my go-to resources are these, in order of importance:
- Reading the Kodi API documentation: https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmc.html
- Reading the Kodi official wikis: https://kodi.wiki/view/Add-on_development
- Reading other people's add-ons, directly through Github, or indirectly through things like [ProgramCreek](https://www.programcreek.com/python/?action=search&ClassName=xbmc&submit=Search). This is to know how people write add-ons for it, what techniques they use in their code etc.
- Doing web searches, it will usually point to the Kodi forums with people discussing the subject, the Kodi wikis etc.
