### ISSUE TITLE
no addon icon

### ISSUE THREAD

**Issue by htatla81** [doko-desuka/plugin.program.orderfavourites#9]
hi when installing on Fire stick there is no icon/thumb for the app, just see the generic white box logo

am i doing something wrong?

**Comment by doko-desuka** [comment]
I don't know what that could be. I tried updating the `addon.xml` file to explicitly include an `<icon>` asset, hope it works better.
It's in version 1.2.3 or higher, in the Releases page: https://github.com/doko-desuka/plugin.program.orderfavourites/releases

**Comment by doko-desuka** [comment]
Hi, did you find if the icon was fixed in v1.2.3?

**Comment by htatla81** [comment]
> Hi, did you find if the icon was fixed in v1.2.3?

Yes I the icon is now visible! Thank you. What was the fix for my understanding pls?

**Comment by doko-desuka** [comment]
The only change was the addition of the explicit icon asset into the `addon.xml` file (the "manifest" file that describes the add-on, with its title, description, and some other metadata), seen below:  

https://github.com/doko-desuka/plugin.program.orderfavourites/commit/7f8186d71ddd6fa18dc2adfbfe74469b16f85d9f#diff-11beb51e5598d394e3dfcdd282f505fb089203176e38f3ca50b08e2ff5f4e81fR52-R54
